<?php

namespace Uzsoftic\SitemapGenerator;

use Illuminate\Support\ServiceProvider;

class SitemapGeneratorServiceProvider extends ServiceProvider
{

    public function boot()
    {
        /*
         * Optional methods to load your package assets
         */

        //
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
